# auth
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: auth-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: auth-deployment
  minReplicas: 1
  maxReplicas: 20
  targetCPUUtilizationPercentage: 5
---
# upload
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: upload-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: upload-deployment
  minReplicas: 1
  maxReplicas: 20
  targetCPUUtilizationPercentage: 5
---
# stream
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: stream-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: stream-deployment
  minReplicas: 1
  maxReplicas: 20
  targetCPUUtilizationPercentage: 5
---
# filesystem
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: filesystem-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: filesystem-statefulset
  minReplicas: 1
  maxReplicas: 20
  targetCPUUtilizationPercentage: 5