# mysql
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: mysql-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: mysql-deployment
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 1
---
# auth
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: auth-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: auth-deployment
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 20
---
# filesystem
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: filesystem-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: filesystem-deployment
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 20
---
# upload
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: upload-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: upload-deployment
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 20
---
# stream
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: stream-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: stream-deployment
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 20
