# mysql
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-statefulset
spec:
  serviceName: mysql-service
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: fishfinna/acit-3495-mysql:latest
          ports:
            - containerPort: 3306
          envFrom:
            - configMapRef:
                name: env-configmap
            - secretRef:
                name: password-secret
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pvc

---
# auth
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: fishfinna/acit-3495-authentication:latest
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: env-configmap
            - secretRef:
                name: password-secret

---
# filesystem
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: filesystem-deployment
spec:
  serviceName: filesystem-service
  replicas: 1
  selector:
    matchLabels:
      app: filesystem
  template:
    metadata:
      labels:
        app: filesystem
    spec:
      containers:
        - name: filesystem
          image: fishfinna/acit-3495-filesystem:latest
          ports:
            - containerPort: 8100
          envFrom:
            - configMapRef:
                name: env-configmap

---
# upload
apiVersion: apps/v1
kind: Deployment
metadata:
  name: upload-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: upload
  template:
    metadata:
      labels:
        app: upload
    spec:
      containers:
        - name: upload
          image: fishfinna/acit-3495-upload:latest
          ports:
            - containerPort: 8090
          envFrom:
            - configMapRef:
                name: env-configmap
            - secretRef:
                name: password-secret

---
# stream
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stream-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stream
  template:
    metadata:
      labels:
        app: stream
    spec:
      containers:
        - name: stream
          image: fishfinna/acit-3495-stream:latest
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: env-configmap
            - secretRef:
                name: password-secret
