# mysql
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  claimRef:
    namespace: default
    name: mysql-pvc
  gcePersistentDisk:
    pdName: mysql-pv-disk
    fsType: ext4
    zone: us-west1-b
---
# filesystem
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: file-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: file-data-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  claimRef:
    namespace: default
    name: file-data-pvc
  gcePersistentDisk:
    pdName: files-pv-disk
    fsType: ext4
    zone: us-west1-b
