# mysql
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sql-pv
spec:
  storageClassName: "standard"
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  claimRef:
    namespace: default
    name: mysql-pvc
  csi:
    driver: pd.csi.storage.gke.io
    volumeHandle: projects/acit-3495-406722/zones/us-central1-b/disks/mysql-pv-disk
    fsType: ext4
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
spec:
  storageClassName: "standard"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
# filesystem
apiVersion: v1
kind: PersistentVolume
metadata:
  name: file-pv
spec:
  storageClassName: "standard"
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  claimRef:
    namespace: default
    name: file-data-pvc
  csi:
    driver: pd.csi.storage.gke.io
    volumeHandle: projects/acit-3495-406722/zones/us-central1-b/disks/files-pv-disk
    fsType: ext4
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: file-data-pvc
spec:
  storageClassName: "standard"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi