# mysql service
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  selector:
    app: mysql
  ports:
    - name: "3306"
      protocol: TCP
      port: 3306
      targetPort: 3306
---
# auth service
apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector:
    app: auth
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
---
# filesystem
apiVersion: v1
kind: Service
metadata:
  name: filesystem-service
spec:
  selector:
    app: filesystem
  ports:
    - protocol: TCP
      port: 8100
      targetPort: 8100
  type: LoadBalancer
---
# upload
apiVersion: v1
kind: Service
metadata:
  name: upload-service
spec:
  selector:
    app: upload
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 8090
  type: LoadBalancer
---
# stream
apiVersion: v1
kind: Service
metadata:
  name: stream-service
spec:
  selector:
    app: stream
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
